dotenv: .env

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
  - OpenZeppelin/openzeppelin-contracts@4.8.3

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
      - "@zeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3"

networks:
  #default: Sepolia
  development:
    key_hash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    requestConfirmations: 3
    callbackGasLimit: 1000000
    numWords: 1
    verify : False
  Sepolia:
    price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    vrf_coordinator2: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    link: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    key_hash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    subscriptionId: 1922
    requestConfirmations: 3
    callbackGasLimit: 1000000
    numWords: 1
    verif: True

wallets:
  from_key: ${PRIVATE_KEY}
  account_0: ${KEY_0}
  account_1: ${KEY_1}
